-- Migration: Create pyqs table and public read access policy

CREATE TABLE IF NOT EXISTS pyqs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  question TEXT NOT NULL,
  year INT NOT NULL,
  subject TEXT NOT NULL,
  subject_slug TEXT NOT NULL,
  marks INT NOT NULL DEFAULT 1,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
  options TEXT NOT NULL,
  answer TEXT NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_pyqs_subject_slug ON pyqs(subject_slug);
CREATE INDEX IF NOT EXISTS idx_pyqs_year ON pyqs(year);
CREATE INDEX IF NOT EXISTS idx_pyqs_difficulty ON pyqs(difficulty);

-- Row Level Security (RLS)
ALTER TABLE pyqs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select on pyqs" ON pyqs FOR SELECT USING (true);

-- Sample Seed PYQ Questions (2019-2024 GATE Biotechnology & Core Subjects)
INSERT INTO pyqs (question, year, subject, subject_slug, marks, difficulty, options, answer) VALUES
('Which of the following enzymes is responsible for unwinding the DNA double helix during replication in Escherichia coli?', 2024, 'Molecular Biology', 'molecular-biology', 1, 'Easy', 'A) DNA Polymerase I  B) DnaB Helicase  C) Topoisomerase II  D) Primase', 'B'),
('Michaelis-Menten kinetics of an enzyme-catalyzed reaction yields KM = 5 mM. At a substrate concentration of 15 mM, the reaction velocity is what percentage of Vmax?', 2023, 'Biochemistry', 'biochemistry', 2, 'Medium', 'A) 50%  B) 66.7%  C) 75%  D) 80%', 'C'),
('In a stirred tank bioreactor, the oxygen transfer rate (OTR) increases directly with an increase in:', 2024, 'Bioprocess Engineering', 'bioprocess-engineering', 2, 'Medium', 'A) Volumetric mass transfer coefficient (kLa)  B) Liquid volume  C) Viscosity of fermentation broth  D) Substrate concentration', 'A'),
('Which antibody isotype is primarily present in human mucosal secretions such as saliva, tears, and colostrum?', 2022, 'Immunology', 'immunology', 1, 'Easy', 'A) IgG  B) IgM  C) IgA  D) IgE', 'C'),
('During cell division, sister chromatids are held together by a protein complex called:', 2023, 'Cell Biology', 'cell-biology', 1, 'Easy', 'A) Cohesin  B) Condensin  C) Kinesin  D) Tubulin', 'A'),
('In Recombinant DNA Technology, which enzyme is utilized to generate complementary DNA (cDNA) from an mRNA template?', 2024, 'Recombinant DNA Technology', 'recombinant-dna-technology', 1, 'Easy', 'A) Taq Polymerase  B) Reverse Transcriptase  C) DNA Ligase  D) Restriction Endonuclease', 'B'),
('What is the probability of obtaining an AABB offspring from a cross between two heterozygous Parents (AaBb x AaBb)?', 2023, 'Genetics', 'genetics', 2, 'Medium', 'A) 1/4  B) 1/8  C) 1/16  D) 9/16', 'C'),
('BLAST (Basic Local Alignment Search Tool) algorithm uses which approach for fast sequence comparison?', 2024, 'Bioinformatics', 'bioinformatics', 1, 'Easy', 'A) Needleman-Wunsch Dynamic Programming  B) Heuristic Seed Matching  C) Smith-Waterman Alignment  D) Markov Chain Monte Carlo', 'B'),
('The primary function of Agrobacterium tumefaciens T-DNA during plant transformation is to insert into:', 2022, 'Plant Biotechnology', 'plant-biotechnology', 2, 'Hard', 'A) Chloroplast DNA  B) Plant Nuclear Genome  C) Mitochondrial DNA  D) Cell Wall Glycoproteins', 'B'),
('Monoclonal antibodies of specified antigen specificity are commercially produced by fusing myeloma cells with:', 2021, 'Animal Biotechnology', 'animal-biotechnology', 1, 'Easy', 'A) T-lymphocytes  B) B-lymphocytes (Plasma cells)  C) Macrophages  D) Fibroblasts', 'B'),
('Which of the following organic reactions follows an SN1 mechanism characterized by a carbocation intermediate?', 2023, 'Pharmaceutical Organic Chemistry I', 'pharmaceutical-organic-chemistry-1', 2, 'Medium', 'A) Hydrolysis of tert-butyl bromide  B) Reaction of primary alcohol with HBr  C) Bromination of benzene  D) Dehydration of ethanol', 'A'),
('A complete turn of a standard B-DNA double helix contains approximately how many base pairs?', 2024, 'General Aptitude', 'general-aptitude', 1, 'Easy', 'A) 10.5  B) 12  C) 8.5  D) 15', 'A'),
('Thermal death time (TDT) of micro-organisms during thermal sterilization is defined as time required to kill:', 2022, 'Microbiology', 'microbiology', 2, 'Medium', 'A) 90% of population at given temp  B) 100% of population at given temp  C) 50% of population at given temp  D) 99.9% of population', 'B'),
('Which parameter is used in downstream processing to characterize the resolution of two chromatographic peaks?', 2021, 'Downstream Processing', 'downstream-processing', 2, 'Hard', 'A) Retention volume  B) Peak capacity  C) Separation factor & resolution (Rs)  D) Void volume', 'C'),
('Which structural element in proteins is predominantly stabilized by intrachain hydrogen bonds parallel to the helix axis?', 2020, 'Biochemistry', 'biochemistry', 1, 'Easy', 'A) Beta-pleated sheet  B) Alpha-helix  C) Reverse turn  D) Random coil', 'B')
ON CONFLICT DO NOTHING;
