-- Migration for paper_plans table (All GATE Papers)
CREATE TABLE IF NOT EXISTS public.paper_plans (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  paper text NOT NULL,
  code text NOT NULL UNIQUE,
  category text NOT NULL,
  target_year text NOT NULL DEFAULT 'GATE 2025/2026',
  priority text NOT NULL DEFAULT 'Reference',
  notes text,
  syllabus_pdf text NOT NULL DEFAULT '#',
  youtube text NOT NULL DEFAULT '#',
  pdf_resources text NOT NULL DEFAULT '#',
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.paper_plans ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public paper_plans read access" ON public.paper_plans
  FOR SELECT USING (true);

-- Insert GATE papers seed data
INSERT INTO public.paper_plans (paper, code, category, target_year, priority, notes, syllabus_pdf, youtube, pdf_resources) VALUES
('Biotechnology', 'BT', 'Life Sciences & Bioengineering', 'GATE 2025/2026', 'Primary', 'Primary target paper for GateBT Prep. Complete study notes, syllabus breakdown, PYQs, and video tutorials available.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/bt.pdf', 'https://www.youtube.com/results?search_query=gate+biotechnology+lectures', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Biomedical Engineering', 'BM', 'Life Sciences & Bioengineering', 'GATE 2025/2026', 'Secondary', 'Secondary paper for BT candidates. Covers bioinstrumentation, medical imaging, and biomechanics.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/bm.pdf', 'https://www.youtube.com/results?search_query=gate+biomedical+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Life Sciences', 'XL', 'Life Sciences & Bioengineering', 'GATE 2025/2026', 'Secondary', 'Popular combination for BT aspirants. Chemistry is compulsory + choice of 2 subjects (Biochemistry, Botany, Zoology, Microbiology, Food Tech).', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/xl.pdf', 'https://www.youtube.com/results?search_query=gate+life_sciences+xl', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Ecology and Evolution', 'EY', 'Life Sciences & Bioengineering', 'GATE 2025/2026', 'Secondary', 'Overlapping concepts in population genetics, ecology, and evolutionary biology.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ey.pdf', 'https://www.youtube.com/results?search_query=gate+ecology+evolution', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Chemical Engineering', 'CH', 'Engineering', 'GATE 2025/2026', 'Secondary', 'Core engineering concepts overlapping with Bioprocess Engineering & Fluid Dynamics.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ch.pdf', 'https://www.youtube.com/results?search_query=gate+chemical+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Chemistry', 'CY', 'Sciences', 'GATE 2025/2026', 'Secondary', 'Physical, Organic, and Inorganic Chemistry paper for core science background students.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/cy.pdf', 'https://www.youtube.com/results?search_query=gate+chemistry+preparation', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Environmental Science and Engineering', 'ES', 'Environmental & Earth Sciences', 'GATE 2025/2026', 'Secondary', 'Interdisciplinary paper with biological waste treatment and environmental microbiology syllabus.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/es.pdf', 'https://www.youtube.com/results?search_query=gate+environmental+science', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Engineering Sciences', 'XE', 'Engineering', 'GATE 2025/2026', 'Secondary', 'Flexible paper choice (Engg Math compulsory + Fluid Mechanics, Thermodynamics, Materials, Polymer, Food Tech).', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/xe.pdf', 'https://www.youtube.com/results?search_query=gate+engineering+sciences+xe', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Data Science and Artificial Intelligence', 'DA', 'Computer Science & IT', 'GATE 2025/2026', 'Secondary', 'Newly introduced GATE paper covering Python, Machine Learning, Linear Algebra, and Statistics.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/da.pdf', 'https://www.youtube.com/results?search_query=gate+data+science+da', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Mathematics', 'MA', 'Sciences', 'GATE 2025/2026', 'Secondary', 'Pure and Applied Mathematics paper for quantitative candidates.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ma.pdf', 'https://www.youtube.com/results?search_query=gate+mathematics', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Physics', 'PH', 'Sciences', 'GATE 2025/2026', 'Secondary', 'Core Physics paper covering Quantum Mechanics, Electrodynamics, and Thermodynamics.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ph.pdf', 'https://www.youtube.com/results?search_query=gate+physics', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Statistics', 'ST', 'Sciences', 'GATE 2025/2026', 'Secondary', 'Probability theory, inference, stochastic processes, and multivariate analysis.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/st.pdf', 'https://www.youtube.com/results?search_query=gate+statistics', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Aerospace Engineering', 'AE', 'Engineering', 'GATE 2025/2026', 'Reference', 'Aerodynamics, Flight Mechanics, Propulsion, and Structures.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ae.pdf', 'https://www.youtube.com/results?search_query=gate+aerospace+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Agricultural Engineering', 'AG', 'Engineering', 'GATE 2025/2026', 'Reference', 'Farm Machinery, Soil and Water Conservation, Irrigation, and Food Processing.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ag.pdf', 'https://www.youtube.com/results?search_query=gate+agricultural+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Architecture and Planning', 'AR', 'Design & Architecture', 'GATE 2025/2026', 'Reference', 'Architecture Design, Building Materials, Urban Planning, and Environmental Services.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ar.pdf', 'https://www.youtube.com/results?search_query=gate+architecture+planning', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Civil Engineering', 'CE', 'Engineering', 'GATE 2025/2026', 'Reference', 'Structural, Geotechnical, Water Resources, Transportation, and Environmental Engineering.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ce.pdf', 'https://www.youtube.com/results?search_query=gate+civil+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Computer Science & Information Tech', 'CS', 'Computer Science & IT', 'GATE 2025/2026', 'Reference', 'Data Structures, Algorithms, DBMS, Operating Systems, Computer Networks, and Theory of Computation.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/cs.pdf', 'https://www.youtube.com/results?search_query=gate+computer+science', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Electronics and Communication Eng.', 'EC', 'Engineering', 'GATE 2025/2026', 'Reference', 'Signals & Systems, Analog Circuits, Digital Circuits, Communications, and Electromagnetics.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ec.pdf', 'https://www.youtube.com/results?search_query=gate+electronics+communication', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Electrical Engineering', 'EE', 'Engineering', 'GATE 2025/2026', 'Reference', 'Electric Circuits, Power Systems, Electrical Machines, Control Systems, and Power Electronics.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ee.pdf', 'https://www.youtube.com/results?search_query=gate+electrical+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Geomatics Engineering', 'GE', 'Engineering', 'GATE 2025/2026', 'Reference', 'Remote Sensing, GIS, GNSS, Surveying, and Digital Image Processing.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/ge.pdf', 'https://www.youtube.com/results?search_query=gate+geomatics+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Geology and Geophysics', 'GG', 'Environmental & Earth Sciences', 'GATE 2025/2026', 'Reference', 'Earth Systems, Mineralogy, Petrology, Seismology, and Gravity & Magnetic Fields.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/gg.pdf', 'https://www.youtube.com/results?search_query=gate+geology+geophysics', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Instrumentation Engineering', 'IN', 'Engineering', 'GATE 2025/2026', 'Reference', 'Sensors, Transducers, Industrial Instrumentation, Control Systems, and Biomedical Instruments.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/in.pdf', 'https://www.youtube.com/results?search_query=gate+instrumentation+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Mechanical Engineering', 'ME', 'Engineering', 'GATE 2025/2026', 'Reference', 'Thermodynamics, Fluid Mechanics, Heat Transfer, Machine Design, and Manufacturing.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/me.pdf', 'https://www.youtube.com/results?search_query=gate+mechanical+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Mining Engineering', 'MN', 'Engineering', 'GATE 2025/2026', 'Reference', 'Mine Surveying, Rock Mechanics, Surface Mining, Mine Ventilation, and Safety.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/mn.pdf', 'https://www.youtube.com/results?search_query=gate+mining+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Metallurgical Engineering', 'MT', 'Engineering', 'GATE 2025/2026', 'Reference', 'Physical Metallurgy, Extractive Metallurgy, Thermodynamics, and Mechanical Metallurgy.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/mt.pdf', 'https://www.youtube.com/results?search_query=gate+metallurgical+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Naval Architecture & Marine Eng.', 'NM', 'Engineering', 'GATE 2025/2026', 'Reference', 'Ship Hydrostatics, Marine Hydrodynamics, Ship Structures, and Marine Machinery.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/nm.pdf', 'https://www.youtube.com/results?search_query=gate+naval+architecture', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Petroleum Engineering', 'PE', 'Engineering', 'GATE 2025/2026', 'Reference', 'Drilling Engineering, Reservoir Engineering, Petroleum Production, and Enhanced Oil Recovery.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/pe.pdf', 'https://www.youtube.com/results?search_query=gate+petroleum+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Production and Industrial Eng.', 'PI', 'Engineering', 'GATE 2025/2026', 'Reference', 'Casting, Joining, Machining, Operations Research, Quality Control, and Supply Chain Management.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/pi.pdf', 'https://www.youtube.com/results?search_query=gate+production+industrial', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Textile Engineering and Fibre Science', 'TF', 'Engineering', 'GATE 2025/2026', 'Reference', 'Textile Fibres, Yarn Manufacture, Fabric Manufacture, Testing, and Chemical Processing.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/tf.pdf', 'https://www.youtube.com/results?search_query=gate+textile+engineering', 'https://gate2024.iisc.ac.in/previous-question-papers/'),
('Humanities and Social Sciences', 'XH', 'Humanities', 'GATE 2025/2026', 'Reference', 'Economics, English, Linguistics, Philosophy, Psychology, and Sociology.', 'https://gate2024.iisc.ac.in/wp-content/uploads/2023/07/xh.pdf', 'https://www.youtube.com/results?search_query=gate+humanities+social+sciences', 'https://gate2024.iisc.ac.in/previous-question-papers/')
ON CONFLICT (code) DO NOTHING;
