-- Migration: Update paper_plans for GATE 2027 Official IIT Madras 30-Paper List
-- Description: Idempotently upserts all 30 official GATE 2027 papers with verified direct IIT Madras syllabus PDF URLs.

-- 1. Ensure required metadata columns exist
ALTER TABLE public.paper_plans
ADD COLUMN IF NOT EXISTS source_name TEXT DEFAULT 'GATE 2027 IIT Madras',
ADD COLUMN IF NOT EXISTS source_url TEXT DEFAULT 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus',
ADD COLUMN IF NOT EXISTS is_official BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS syllabus_year INTEGER DEFAULT 2027,
ADD COLUMN IF NOT EXISTS is_revised BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 2. Create unique index on code to enable ON CONFLICT DO UPDATE
CREATE UNIQUE INDEX IF NOT EXISTS paper_plans_code_unique ON public.paper_plans(code);

-- 3. Upsert official 30 GATE 2027 papers dataset
INSERT INTO public.paper_plans (
  paper, code, category, target_year, priority, notes, syllabus_pdf, youtube, pdf_resources, source_name, source_url, is_official, syllabus_year, is_revised, updated_at
) VALUES
('Biotechnology', 'BT', 'Life Sciences & Bioengineering', 'GATE 2027', 'Primary', 'Primary target paper for GateBT Prep. Complete revised GATE 2027 syllabus breakdown, notes, PYQs, and video lectures.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/BT_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+biotechnology+lectures', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Life Sciences', 'XL', 'Life Sciences & Bioengineering', 'GATE 2027', 'Secondary', 'Chemistry compulsory + 2 choices (Biochemistry, Botany, Zoology, Microbiology, Food Tech). Revised syllabus.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/XL_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+life_sciences+xl', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Biomedical Engineering', 'BM', 'Life Sciences & Bioengineering', 'GATE 2027', 'Secondary', 'Bioinstrumentation, medical imaging, biomaterials, and biomechanics syllabus.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/BM_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+biomedical+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Ecology and Evolution', 'EY', 'Life Sciences & Bioengineering', 'GATE 2027', 'Secondary', 'Population genetics, behavioral ecology, evolutionary biology, and quantitative ecology.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/EY_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+ecology+evolution', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Chemical Engineering', 'CH', 'Engineering', 'GATE 2027', 'Secondary', 'Process calculations, thermodynamics, fluid mechanics, heat and mass transfer.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/CH_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+chemical+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Chemistry', 'CY', 'Sciences', 'GATE 2027', 'Secondary', 'Physical Chemistry, Organic Chemistry, and Inorganic Chemistry syllabus.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/CY_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+chemistry+preparation', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Environmental Science and Engineering', 'ES', 'Environmental & Earth Sciences', 'GATE 2027', 'Secondary', 'Environmental microbiology, water treatment, air pollution, and environmental management.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/ES_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+environmental+science', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Engineering Sciences', 'XE', 'Engineering', 'GATE 2027', 'Secondary', 'Engg Mathematics (compulsory) + 2 choices (Fluid Mechanics, Materials, Polymer, Food Tech, etc.).', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/XE_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+engineering+sciences+xe', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Data Science and Artificial Intelligence', 'DA', 'Computer Science & IT', 'GATE 2027', 'Secondary', 'Linear Algebra, Calculus, Probability, Machine Learning, Python, and Database Management.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/DA_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+data+science+da', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Aerospace Engineering', 'AE', 'Engineering', 'GATE 2027', 'Reference', 'Aerodynamics, Flight Mechanics, Propulsion, Aircraft Structures, and Space Dynamics.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/AE_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+aerospace+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Agricultural Engineering', 'AG', 'Engineering', 'GATE 2027', 'Reference', 'Farm Machinery, Soil & Water Conservation, Irrigation, Post-Harvest Tech, and Process Engg.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/AG_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+agricultural+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Architecture and Planning', 'AR', 'Design & Architecture', 'GATE 2027', 'Reference', 'Architecture Design, Building Materials, Urban Planning, Housing, and Environmental Services.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/AR_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+architecture+planning', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Civil Engineering', 'CE', 'Engineering', 'GATE 2027', 'Reference', 'Structural, Geotechnical, Water Resources, Transportation, Geomatics, and Environmental Engg.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/CE_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+civil+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Computer Science and Information Technology', 'CS', 'Computer Science & IT', 'GATE 2027', 'Reference', 'Data Structures, Algorithms, DBMS, Operating Systems, Computer Networks, TOC, and Compilers.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/CS_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+computer+science', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Electronics and Communication Engineering', 'EC', 'Engineering', 'GATE 2027', 'Reference', 'Network Theory, Signals & Systems, Analog & Digital Circuits, Control Systems, Communications.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/EC_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+electronics+communication', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Electrical Engineering', 'EE', 'Engineering', 'GATE 2027', 'Reference', 'Electric Circuits, Electromagnetic Fields, Signals, Machines, Power Systems, Power Electronics.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/EE_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+electrical+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Geomatics Engineering', 'GE', 'Engineering', 'GATE 2027', 'Reference', 'Remote Sensing, GIS, GNSS, Geodesy, Surveying, and Digital Image Processing.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/GE_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+geomatics+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Geology and Geophysics', 'GG', 'Environmental & Earth Sciences', 'GATE 2027', 'Reference', 'Earth Systems, Mineralogy, Structural Geology, Seismology, Gravimetry, and Magnetic Fields.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/GG_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+geology+geophysics', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Instrumentation Engineering', 'IN', 'Engineering', 'GATE 2027', 'Reference', 'Transducers, Industrial Instrumentation, Control Systems, Signals, and Optical Instrumentation.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/IN_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+instrumentation+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Mathematics', 'MA', 'Sciences', 'GATE 2027', 'Reference', 'Linear Algebra, Real Analysis, Complex Analysis, ODEs, PDEs, Algebra, and Topology.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/MA_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+mathematics', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Mechanical Engineering', 'ME', 'Engineering', 'GATE 2027', 'Reference', 'Thermodynamics, Fluid Mechanics, Heat Transfer, Machine Design, and Manufacturing Engg.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/ME_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+mechanical+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Mining Engineering', 'MN', 'Engineering', 'GATE 2027', 'Reference', 'Mine Surveying, Rock Mechanics, Surface Mining, Mine Ventilation, and Safety Systems.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/MN_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+mining+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Metallurgical Engineering', 'MT', 'Engineering', 'GATE 2027', 'Reference', 'Physical Metallurgy, Extractive Metallurgy, Thermodynamics, and Mechanical Metallurgy.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/MT_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+metallurgical+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Naval Architecture and Marine Engineering', 'NM', 'Engineering', 'GATE 2027', 'Reference', 'Ship Hydrostatics, Marine Hydrodynamics, Ship Structures, and Marine Machinery Systems.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/NM_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+naval+architecture', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Petroleum Engineering', 'PE', 'Engineering', 'GATE 2027', 'Reference', 'Drilling Engineering, Reservoir Engineering, Petroleum Production, and Enhanced Oil Recovery.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/PE_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+petroleum+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Physics', 'PH', 'Sciences', 'GATE 2027', 'Reference', 'Mathematical Physics, Quantum Mechanics, Thermodynamics, Electrodynamics, and Solid State.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/PH_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+physics', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Production and Industrial Engineering', 'PI', 'Engineering', 'GATE 2027', 'Reference', 'Casting, Joining, Machining, Operations Research, Quality Control, and Supply Chain.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/PI_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+production+industrial', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Robotics and Automation', 'RA', 'Engineering', 'GATE 2027', 'Reference', 'Robot Kinematics, Control Systems, Actuators, Sensors, Computer Vision, and Automation.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/RA_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+robotics+automation', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Statistics', 'ST', 'Sciences', 'GATE 2027', 'Reference', 'Probability Theory, Estimation, Hypothesis Testing, Stochastic Processes, and Multivariate Analysis.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/ST_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+statistics', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Textile Engineering and Fibre Science', 'TF', 'Engineering', 'GATE 2027', 'Reference', 'Textile Fibres, Yarn Manufacture, Fabric Manufacture, Testing, and Chemical Processing.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/TF_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+textile+engineering', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW()),
('Humanities and Social Sciences', 'XH', 'Humanities', 'GATE 2027', 'Reference', 'Reasoning & Comprehension compulsory + Economics, English, Linguistics, Philosophy, Psychology, Sociology.', 'https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/XH_GATE2027_Syllabus.pdf', 'https://www.youtube.com/results?search_query=gate+humanities+social+sciences', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', 'GATE 2027 IIT Madras', 'https://gate2027.iitm.ac.in/exam_papers_and_syllabus', true, 2027, true, NOW())
ON CONFLICT (code) DO UPDATE SET
  paper = EXCLUDED.paper,
  category = EXCLUDED.category,
  target_year = EXCLUDED.target_year,
  priority = EXCLUDED.priority,
  notes = EXCLUDED.notes,
  syllabus_pdf = EXCLUDED.syllabus_pdf,
  youtube = EXCLUDED.youtube,
  pdf_resources = EXCLUDED.pdf_resources,
  source_name = EXCLUDED.source_name,
  source_url = EXCLUDED.source_url,
  is_official = EXCLUDED.is_official,
  syllabus_year = EXCLUDED.syllabus_year,
  is_revised = EXCLUDED.is_revised,
  updated_at = NOW();
