-- Migration: Create resource_library table, RLS, and seed dataset

CREATE TABLE IF NOT EXISTS resource_library (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('Book', 'PDF', 'Video', 'Website')),
  subject TEXT NOT NULL,
  subject_slug TEXT NOT NULL,
  link TEXT NOT NULL,
  rating NUMERIC(3, 1)
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_resource_library_subject_slug ON resource_library(subject_slug);
CREATE INDEX IF NOT EXISTS idx_resource_library_type ON resource_library(type);

-- Row Level Security (RLS)
ALTER TABLE resource_library ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select on resource_library" ON resource_library FOR SELECT USING (true);

-- Seed 22 Curated High-Yield Resources for GATE BT & B.Pharm
INSERT INTO resource_library (name, type, subject, subject_slug, link, rating) VALUES
('Lehninger Principles of Biochemistry (Nelson & Cox)', 'Book', 'Biochemistry', 'biochemistry', 'https://archive.org/details/lehninger-principles-of-biochemistry-7th-edition', 9.8),
('NPTEL Video Course: Biochemistry by Prof. Swagata Dasgupta (IIT KGP)', 'Video', 'Biochemistry', 'biochemistry', 'https://nptel.ac.in/courses/102105034', 9.5),
('Molecular Biology of the Cell (Alberts et al.)', 'Book', 'Molecular Biology', 'molecular-biology', 'https://www.ncbi.nlm.nih.gov/books/NBK21054/', 9.9),
('Khan Academy: DNA Replication, Transcription & Translation', 'Video', 'Molecular Biology', 'molecular-biology', 'https://www.khanacademy.org/science/biology/gene-expression-central-dogma', 9.4),
('Prescott’s Microbiology (Willey et al.)', 'Book', 'Microbiology', 'microbiology', 'https://archive.org/details/prescotts-microbiology-10th-edition', 9.6),
('Kuby Immunology (Punt, Stranford, Jones, Owen)', 'Book', 'Immunology', 'immunology', 'https://archive.org/details/kuby-immunology-8th-edition', 9.7),
('Principles of Gene Manipulation and Genomics (Primrose & Twyman)', 'Book', 'Recombinant DNA Technology', 'recombinant-dna-technology', 'https://archive.org/details/principles-of-gene-manipulation', 9.5),
('NCBI Molecular Biology Techniques & PCR Protocols Handbook', 'PDF', 'Recombinant DNA Technology', 'recombinant-dna-technology', 'https://www.ncbi.nlm.nih.gov/pmc/', 9.2),
('Bioprocess Engineering Principles (Pauline M. Doran)', 'Book', 'Bioprocess Engineering', 'bioprocess-engineering', 'https://archive.org/details/bioprocess-engineering-principles-doran', 9.8),
('NPTEL Bioprocess Engineering Video Series (IIT Madras)', 'Video', 'Bioprocess Engineering', 'bioprocess-engineering', 'https://nptel.ac.in/courses/102106022', 9.6),
('Protein Purification Protocols & Chromatography Guide (GE Healthcare)', 'PDF', 'Downstream Processing', 'downstream-processing', 'https://www.cytivalifesciences.com/en/us/solutions/protein-purification', 9.4),
('Principles of Genetics (Snustad & Simmons)', 'Book', 'Genetics', 'genetics', 'https://archive.org/details/principles-of-genetics-snustad', 9.4),
('NCBI BLAST Quick Reference & Algorithm Tutorial', 'Website', 'Bioinformatics', 'bioinformatics', 'https://blast.ncbi.nlm.nih.gov/Blast.cgi', 9.7),
('Bioinformatics: Sequence and Genome Analysis (David W. Mount)', 'Book', 'Bioinformatics', 'bioinformatics', 'https://archive.org/details/bioinformatics-mount', 9.3),
('Plant Biotechnology: The Genetic Manipulation of Plants (Slater et al.)', 'Book', 'Plant Biotechnology', 'plant-biotechnology', 'https://archive.org/details/plant-biotechnology-slater', 9.1),
('Culture of Animal Cells: A Manual of Basic Technique (R. Ian Freshney)', 'Book', 'Animal Biotechnology', 'animal-biotechnology', 'https://archive.org/details/freshney-animal-cell-culture', 9.5),
('Advanced Engineering Mathematics (Erwin Kreyszig)', 'Book', 'Engineering Mathematics', 'engineering-mathematics', 'https://archive.org/details/advanced-engineering-mathematics-kreyszig', 9.6),
('GATE Aptitude Formulae & Practice Questions (IIT GATE Portal)', 'PDF', 'General Aptitude', 'general-aptitude', 'https://gate2024.iisc.ac.in/', 9.3),
('Foye’s Principles of Medicinal Chemistry (Lemke et al.)', 'Book', 'Medicinal Chemistry I', 'medicinal-chemistry-1', 'https://archive.org/details/foyes-principles-medicinal-chemistry', 9.7),
('Trease and Evans Pharmacognosy (Evans)', 'Book', 'Pharmacognosy & Phytochemistry I', 'pharmacognosy-phytochemistry-1', 'https://archive.org/details/trease-and-evans-pharmacognosy', 9.6),
('Organic Chemistry by Morrison & Boyd', 'Book', 'Pharmaceutical Organic Chemistry I', 'pharmaceutical-organic-chemistry-1', 'https://archive.org/details/organic-chemistry-morrison-boyd', 9.8),
('PharmaPathshala & DBATU B.Pharmacy Official Curriculum Guides', 'Website', 'Pharmaceutical Organic Chemistry I', 'pharmaceutical-organic-chemistry-1', 'https://dbatu.ac.in/', 9.2)
ON CONFLICT DO NOTHING;
